# Resource Limits and Requests for All Stateless Services
# Apply these patches to add resource limits to deployments
# Usage: kubectl patch deployment <name> -n microservices --patch-file=<this-file>

---
# Config Server Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: config-server
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# API Gateway Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 1Gi

---
# Auth Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# User Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: user-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Product Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Cart Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: cart-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Order Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: order-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Warranty Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warranty-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: warranty-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Notification Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: notification-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Blog Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: blog-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Report Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: report-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Media Service Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: media-service
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Admin Frontend Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: admin-frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
# Dealer Frontend Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-frontend
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: dealer-frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
# Main Frontend Resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: main-frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
