apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app: report-service
