apiVersion: v1
kind: Service
metadata:
  name: warranty-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: warranty-service
