apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  selector:
    app: notification-service
