apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: admin-frontend
