apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: blog-service
