apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: media-service
