apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: cart-service
