server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# Cloudinary Configuration (for all media files)
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:daohufjec}
  api-key: ${CLOUDINARY_API_KEY:872317127931114}
  api-secret: ${CLOUDINARY_API_SECRET:N4qcHq42OqjlyK5GiQoZfk1UXfE}
  secure: ${CLOUDINARY_SECURE:true}

# Logging configuration
logging:
  level:
    com.devwonder.mediaservice: DEBUG
    com.cloudinary: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: ${SWAGGER_API_DOCS_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always