apiVersion: v1
kind: Service
metadata:
  name: dealer-frontend
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dealer-frontend
