apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace/namespace.yaml

  # Storage
  - storage/storage-class.yaml

  # ConfigMaps
  - configmaps/app-config.yaml
  - configmaps/postgres-init-script.yaml

  # Secrets
  - secrets/app-secrets.yaml

  # Infrastructure
  - infrastructure/postgres-statefulset.yaml
  - infrastructure/redis-statefulset.yaml
  - infrastructure/zookeeper-statefulset.yaml
  - infrastructure/kafka-statefulset.yaml

  # Core Services
  - services/config-server
  - services/auth-service
  - services/api-gateway

  # Backend Services
  - services/user-service
  - services/product-service
  - services/cart-service
  - services/order-service
  - services/warranty-service
  - services/notification-service
  - services/blog-service
  - services/report-service
  - services/media-service

  # Frontend (commented until images are built)
  # - frontend/admin
  # - frontend/dealer
  # - frontend/main

  # Autoscaling
  - autoscaling/hpa.yaml

  # Ingress
  - ingress/ingress.yaml
