apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: config-server
