apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - ../../base

# namePrefix: dev-  # Removed to avoid service name mismatches

# Using local images (no tag override needed)
# images:
#   - name: microservice-parent-config-server
#     newTag: latest

# Scale down replicas for dev
replicas:
  - name: config-server
    count: 1
  - name: auth-service
    count: 1
  - name: api-gateway
    count: 1
  - name: user-service
    count: 1
  - name: product-service
    count: 1
  - name: cart-service
    count: 1
  - name: order-service
    count: 1
  - name: warranty-service
    count: 1
  - name: notification-service
    count: 1
  - name: blog-service
    count: 1
  - name: report-service
    count: 1
  - name: media-service
    count: 1
  # Frontend replicas (commented until images are built)
  # - name: admin-frontend
  #   count: 1
  # - name: dealer-frontend
  #   count: 1
  # - name: main-frontend
  #   count: 1

# Add dev-specific labels
labels:
  - pairs:
      environment: dev

# Reduce resources for dev (only apply to services, not infrastructure)
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
    target:
      kind: Deployment
      labelSelector: "app in (config-server,auth-service,api-gateway,user-service,product-service,cart-service,order-service,warranty-service,notification-service,blog-service,report-service,media-service,admin-frontend,dealer-frontend,main-frontend)"
